### ISSUE TITLE
Netanim

### ISSUE THREAD

**Issue by Samuel-ZDM** [signetlabdei/lorawan#109]
Hello!

I am new to using ns-3. I'm a student and I'm studying about LoRaWAN.
 I was able to simulate the examples, but I wanted some visual examples using Netanim to put in my dissertation. I managed to generate the xml, but when I run it nothing appears in the simulation.

Can you help me with this?

**Comment by DvdMgr** [comment]
Hi! Netanim is not currently supported. There was some discussion on this matter [in this other issue](https://github.com/signetlabdei/lorawan/issues/96), however I'm not sure anything ever came out of it. Unfortunately we currently don't have the bandwidth to implement this swiftly - but let us know if you get to a satisfactory implementation of this, we gladly accept pull requests!

**Comment by Samuel-ZDM** [comment]
Thank you so much for your answer.
In the future I will be able to study more about it, but I just wanted some example to show for my presentation in college, but no problem, I will show the results of the simulations.

I have a question about the energy consumption example, can I ask this same question? My question is when generating the results file, what are the numbers generated?

**Comment by DvdMgr** [comment]
Looking [at these lines](https://github.com/signetlabdei/lorawan/blob/159cc5e8c62430ee2fb15f6ebcda916202004298/examples/energy-model-example.cc#L177), the generated file should contain the remaining energy in the energy source, at each timestamp.

**Comment by Samuel-ZDM** [comment]
Thank you for your answer.

What I was able to understand is that in the second column are the remaining J values. The first column could not understand. Another question I had is how do I add another value to show? I wanted to show the device's V voltage, but I couldn't figure out how to do that.

**Comment by DvdMgr** [comment]
I think you should be able to do so, since the `FileHelper` has a `Set3dFormat` method ([API reference](https://www.nsnam.org/doxygen/classns3_1_1_file_helper.html)), but I'm not sure of the details - you might need to connect the energy trace source to your own callback so that your function is called whenever the energy changes, get the voltage from within your function, and append your data to an aggregator. At the end of the simulation, then, you could print the contents of the aggregator using the `FileHelper`. Take a look at the ns-3 manual entries for [Data Collection](https://www.nsnam.org/docs/manual/html/data-collection.html) and the tutorial entry for [Tracing](https://www.nsnam.org/docs/tutorial/html/tracing.html) for details on this functionality!

**Comment by adnan98ab** [comment]
how did u simulate the examples??

**Comment by idrissa-gif** [comment]
> how did u simulate the examples??

If you ask how to simulate the examples (file.cc) You have to use the follow commandLine  "./ns3 run src/lorawan/examples/network-server-example.cc" or "./waf run src/lorawan/examples/network-server-example.cc" depending on the version of ns3 you are using.

the commandLine must be open at ns3.xx  at folder or add ns3 to the environment variable

For more understanding read the Readme file

Hope this answer you question !
