### ISSUE TITLE
Fcnt for uplink should not be incremented for retransmission

### ISSUE THREAD

**Issue by theelbowclaps** [signetlabdei/lorawan#68]
## Expected Behavior
Same as title.
According to lorawan spec 1.0.3 (https://lora-alliance.org/sites/default/files/2018-07/lorawan1.0.3.pdf), section **4.3.1.5 ** (ln 520-530) seems to suggest retransmitted frame's Fcnt should not be incremented. Similar idea is expressed in sect **4.3.1.1** ln 443-444.

## Actual Behavior
end-device-lorawan-mac.cc line 291:  m_currentFCnt++;

## Steps to Reproduce the Problem
N/A

## Specifications
N/A

**Comment by DvdMgr** [comment]
Thanks for pointing this out. 

Actually, frame counters have not been implemented/tested so far, as their behavior does not impact the outcome of simulations we are interested in. If you want to implement them correctly also at the `NetworkServer`, please submit a pull request and I'll look into it! Otherwise, I can just remove the line you pointed out to fix this.

**Comment by gaurivn** [comment]
On clicking the link provided in the issue, it says page not found, could you please provide the working link

> ## Expected Behavior
> Same as title.
> According to lorawan spec 1.0.3 (https://lora-alliance.org/sites/default/files/2018-07/lorawan1.0.3.pdf), section **4.3.1.5 ** (ln 520-530) seems to suggest retransmitted frame's Fcnt should not be incremented. Similar idea is expressed in sect **4.3.1.1** ln 443-444.
> 
> ## Actual Behavior
> end-device-lorawan-mac.cc line 291: m_currentFCnt++;
> 
> ## Steps to Reproduce the Problem
> N/A
> 
> ## Specifications
> N/A

**Comment by DvdMgr** [comment]
Hi, searching in the LoRa Alliance website for the 1.0.3 specification as the url suggests brings up this [updated link](https://lora-alliance.org/resource_hub/lorawan-specification-v1-0-3/).
